"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 로컬 빠른 실행용 기본값이라 레포에 그대로 커밋돼 있음(=공개된 값) — 아래에서
# DEBUG=0(배포 모드)일 땐 이 기본값을 쓰지 못하게 강제로 막는다.
_INSECURE_SECRET_KEY = "django-insecure-_2ff$i3f=yv0*o3lp%km=1_&0ab!p^#((_r6mu_mcaox5fm(my"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", _INSECURE_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

if not DEBUG and (not SECRET_KEY or SECRET_KEY == _INSECURE_SECRET_KEY):
    raise ImproperlyConfigured(
        "DJANGO_DEBUG=0(배포 모드)인데 DJANGO_SECRET_KEY 환경변수가 설정되어 있지 "
        "않습니다. 레포에 공개된 기본값을 배포 환경에서 그대로 쓰면 위험하니, "
        ".env에 랜덤한 값을 넣어주세요."
    )

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]

# Render 등 리버스 프록시 뒤에서 배포할 때 필요:
# - CSRF_TRUSTED_ORIGINS: 스킴(https://)까지 포함한 배포 도메인을 넣어야 admin
#   로그인 등 POST 요청에서 CSRF 검증이 통과함 (예: "https://your-app.onrender.com").
# - SECURE_PROXY_SSL_HEADER: Render는 사용자에게는 https로 응답하지만 내부적으로는
#   http로 앱에 전달하므로, 이 헤더가 없으면 Django가 매 요청을 안전하지 않은
#   연결로 오인해 요청이 실제로 https였는지 판단이 어긋난다.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# 기존 구글 폼 → /api/import/google-form 요청 인증용 공유 비밀키.
# google-apps-script/Forwarder.gs의 CONFIG.IMPORT_SECRET과 동일한 값을 넣어야 합니다.
IMPORT_SECRET = os.environ.get("IMPORT_SECRET", "")

# 체크인 시 인포/공연장 점수 시트의 "도착 여부"에 실시간으로 반영하기 위한 공유
# 비밀키. google-apps-script/SheetSync.gs의 CONFIG.SECRET과 동일한 값을 넣어야
# 합니다. 대상 시트 URL은 회차마다 바뀌므로 환경변수가 아니라 Event.sheet_sync_url
# (/admin에서 회차별로 입력)에 넣습니다 — 비워두면 그 회차는 시트 연동 없이
# 체크인만 정상 동작합니다 (기능 자체가 꺼짐).
SHEET_SYNC_SECRET = os.environ.get("SHEET_SYNC_SECRET", "")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "checkin",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    import urllib.parse as _urlparse

    _u = _urlparse.urlparse(DATABASE_URL)
    _qs = _urlparse.parse_qs(_u.query)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _urlparse.unquote(_u.path.lstrip("/")),
            # urlparse는 username/password를 percent-decode하지 않고 원문 그대로
            # 돌려준다 — 비밀번호에 특수문자가 있어 URL 인코딩된 경우(Supabase가
            # 안내하는 방식) unquote 없이 그대로 쓰면 인코딩된 문자열 자체가
            # 비밀번호로 전달돼 인증이 실패한다.
            "USER": _urlparse.unquote(_u.username) if _u.username else _u.username,
            "PASSWORD": _urlparse.unquote(_u.password) if _u.password else _u.password,
            "HOST": _u.hostname,
            "PORT": _u.port or 5432,
            # Render의 관리형 Postgres 등 sslmode가 필요한 연결 문자열 대응
            # (예: "?sslmode=require" — 이 값을 안 넘기면 접속이 거부될 수 있음).
            "OPTIONS": {"sslmode": _qs["sslmode"][0]} if "sslmode" in _qs else {},
        }
    }
else:
    # DATABASE_URL이 없으면 로컬 SQLite로 동작 (빠르게 켜보고 싶을 때용).
    # 실제 운영은 .env.example처럼 PostgreSQL DATABASE_URL을 설정하는 걸 권장합니다.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# whitenoise로 정적 파일을 앱 프로세스 자체가 서빙 (Render 같은 PaaS는 별도
# 웹서버/CDN 없이 gunicorn만 떠 있는 구조라 nginx가 없음).
# 이 해시 매니페스트 스토리지는 collectstatic을 실행해야 {% static %}이 최신
# 파일을 가리킨다 — 로컬 개발(DEBUG=1)에서까지 켜두면 CSS/JS를 고쳐도 매번
# collectstatic을 안 돌리면 브라우저가 예전 파일을 계속 받는 문제가 있었다.
# 배포(DEBUG=0)에서만 매니페스트 스토리지를 쓰고, 로컬에서는 소스 파일을
# 그대로 서빙하게 분리한다.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
