# Generated by Django 5.2.17 on 2026-08-28 02:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(help_text="예: 33", unique=True),
                ),
                (
                    "name",
                    models.CharField(help_text='예: "동방배틀 vol.33"', max_length=200),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="신규 신청을 받는 현재 회차인지"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-volume"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=50)),
                ("school", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "academic_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "payer_name",
                    models.CharField(
                        blank=True,
                        help_text="입금자명 (운영진이 입금 내역과 대조할 때 참고)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("참가", "참가"), ("관람", "관람")], max_length=10
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("N_A", "해당없음"),
                            ("PENDING", "검수 대기"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("PENDING", "대기"), ("PAID", "입금 완료")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("label_group", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "label_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("label_code", models.CharField(blank=True, max_length=10, null=True)),
                ("label_manual_override", models.BooleanField(default=False)),
                ("qr_token", models.UUIDField(blank=True, null=True, unique=True)),
                ("qr_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checkin_status",
                    models.CharField(
                        choices=[
                            ("NOT_CHECKED_IN", "체크인 전"),
                            ("CHECKED_IN", "체크인 완료"),
                        ],
                        default="NOT_CHECKED_IN",
                        max_length=20,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="checkin.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("label_code__isnull", False)),
                        fields=("event", "genre", "label_group", "label_number"),
                        name="label_slot_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("external_ref__isnull", False)),
                        fields=("event", "external_ref"),
                        name="participant_external_ref_unique",
                    ),
                ],
            },
        ),
    ]
