# Generated by Django 5.2.17 on 2026-08-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='label_manual_override',
        ),
    ]
