# Generated by Django 5.2.17 on 2026-08-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_remove_participant_label_manual_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
    ]
