# Generated by Django 5.2.17 on 2026-08-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_remove_participant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='genre',
            field=models.CharField(blank=True, choices=[('Waacking', '왁킹'), ('Popping', '팝핑'), ('Locking', '락킹'), ('House', '하우스'), ('Krump', '크럼프'), ('Hiphop', '힙합'), ('Breaking', '브레이킹')], max_length=100, null=True),
        ),
    ]
