# Generated by Django 5.2.17 on 2026-08-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_alter_participant_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sheet_sync_url',
            field=models.URLField(blank=True, help_text='이 회차 점수 시트에 배포한 SheetSync.gs 웹 앱 URL (선택)', null=True),
        ),
    ]
