# Generated by Django 5.2.17 on 2026-08-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_event_sheet_sync_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-volume'], 'permissions': [('export_sensitive_data', '마스킹 없는 민감 정보 엑셀 내보내기 가능 (점수표, CSV 백업)')]},
        ),
    ]
