# Generated by Django 5.2.17 on 2026-08-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, help_text='행사 당일 날짜 (선택)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='행사 장소 (선택, 예: 국민대학교)', max_length=200, null=True),
        ),
    ]
