# Generated by Django 5.2.17 on 2026-08-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_event_event_date_event_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-volume'], 'permissions': [('export_sensitive_data', '마스킹 없는 민감 정보 엑셀 내보내기 가능 (점수표, CSV 백업)')], 'verbose_name': '회차', 'verbose_name_plural': '회차'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-created_at'], 'verbose_name': '참가자', 'verbose_name_plural': '참가자'},
        ),
    ]
