# Generated by Django 5.2.17 on 2026-08-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_alter_event_options_alter_participant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', '대기'), ('PAID', '입금 완료'), ('REFUND', '환불')], default='PENDING', max_length=10),
        ),
    ]
