# Generated by Django 5.2.17 on 2026-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0009_alter_participant_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='verification_note',
            field=models.TextField(blank=True, help_text='학적검수 메모 (반려 사유 등 운영진 참고용, 참가자에게는 노출되지 않음)', null=True),
        ),
    ]
