# Generated by Django 5.2.17 on 2026-09-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0010_participant_verification_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-volume'], 'permissions': [('export_sensitive_data', '마스킹 없는 민감 정보 엑셀 내보내기 가능 (점수표, CSV 백업)'), ('run_label_assign', '라벨 · QR 발급 실행 가능'), ('push_order_to_sheet', '점수 시트 순서 반영 가능')], 'verbose_name': '회차', 'verbose_name_plural': '회차'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-created_at'], 'permissions': [('use_scanner', '현장 체크인 스캐너 사용 가능'), ('approve_verification', '학적검수 승인 처리 가능'), ('mark_paid', '입금 확인 처리 가능'), ('mark_refund', '환불 처리 가능'), ('swap_labels', '라벨 맞바꾸기 가능')], 'verbose_name': '참가자', 'verbose_name_plural': '참가자'},
        ),
    ]
