# Generated by Django 5.2.17 on 2026-09-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0014_suggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-created_at'], 'permissions': [('scan_qr', '체크인 스캐너에서 QR 스캔 사용 가능'), ('search_manual', '체크인 스캐너에서 이름/전화 수동 검색 사용 가능'), ('approve_verification', '학적검수 승인 처리 가능'), ('mark_paid', '입금 확인 처리 가능'), ('mark_refund', '환불 처리 가능'), ('swap_labels', '라벨 맞바꾸기 가능')], 'verbose_name': '참가자', 'verbose_name_plural': '참가자'},
        ),
    ]
